### ISSUE TITLE
Error while building library

### ISSUE THREAD

**Issue by salas81** [maximkulkin/esp-wolfssl#6]
I'm getting this error while building this library for the HomeKit framework in esp-idf

Multiple ways to build the same target were specified for: /Users/Lorenzo/Documents/PlatformIO/Projects/FastLedTestArd/.pio/build/esp32dev/lib213/esp-wolfssl/wolfssl-4.1.0/wolfcrypt/src/aes_asm.o  (from ['/Users/Lorenzo/Documents/PlatformIO/Projects/FastLedTestArd/.pio/libdeps/esp32dev/esp-wolfssl/wolfssl-4.1.0/wolfcrypt/src/aes_asm.S'] and from ['/Users/Lorenzo/Documents/PlatformIO/Projects/FastLedTestArd/.pio/libdeps/esp32dev/esp-wolfssl/wolfssl-4.1.0/wolfcrypt/src/aes_asm.asm'])

any hint?

**Comment by maximkulkin** [comment]
Your IDE is picking files that are not supposed to be built. Either tweak project in your IDE or just use console build.
